In [1]:
##numpy array
import numpy as np

In [2]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[3,4,5,6,7]
arr=np.array([l1,l2,l3])

In [3]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [4]:
arr[:,1]

array([2, 3, 4])

In [5]:
arr[1:,1:3]

array([[3, 4],
       [4, 5]])

In [6]:
arr[0::2,0:]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [7]:
lst1=[1,2,3,4]
arr1=np.array(lst1)
arr1

array([1, 2, 3, 4])

In [8]:
arr1<2

array([ True, False, False, False])

In [9]:
arr1[arr1<2]

array([1])

In [10]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [14]:
arr1

array([1, 2, 3, 4])

In [15]:
arr1*arr1

array([ 1,  4,  9, 16])

In [16]:
arr*arr

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [17]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.random.randint(10,50,4)

array([13, 29, 36, 21])

In [20]:
np.random.randint(10,50,4).reshape(2,2)

array([[39, 48],
       [10, 35]])

In [21]:
np.random.randn(5,6)

array([[-1.42839564, -1.76429907,  0.10251037, -0.77570566,  2.11151178,
        -0.35104832],
       [ 0.09333267, -2.53037187, -0.16752034,  0.20778055, -1.38713534,
        -0.57928095],
       [-0.87943676, -0.45321655, -0.67217405, -0.93640097,  0.4816415 ,
        -0.55311394],
       [-1.67073972, -2.29694636, -0.34083613,  0.30266962, -0.72915309,
         0.02403704],
       [ 0.99370641,  0.35610365,  1.05897266, -1.34200073,  1.08775732,
        -0.84740939]])

In [22]:
np.random.random_sample((4,7))

array([[0.23067222, 0.73886522, 0.12127024, 0.70199235, 0.79396998,
        0.38637186, 0.29323895],
       [0.87714528, 0.32099216, 0.62526152, 0.02581107, 0.96815164,
        0.9788681 , 0.65551628],
       [0.87344291, 0.46877685, 0.93276073, 0.5957953 , 0.88207484,
        0.25542527, 0.79616548],
       [0.4276701 , 0.320846  , 0.06279067, 0.81864239, 0.8256522 ,
        0.10829997, 0.23104296]])